# 🐼 100 Pandas Practical Questions — With Answers

This notebook contains solved answers for all 100 practice questions, organized into 5 sections:

1. Basics & Series (Q1–Q20)
2. Indexing, Selection & Slicing (Q21–Q40)
3. Data Cleaning (Q41–Q60)
4. Data Manipulation (Q61–Q80)
5. Iteration, GroupBy & Pivot (Q81–Q100)

Run the **Setup** cell first — every later answer depends on the sample `df` and `s` it creates.

## ⚙️ Setup — Sample Data

Run this cell first. It creates a sample Series `s` and a sample employee `DataFrame` `df` (deliberately messy: missing values, duplicates, mixed-case strings, extra whitespace, and a salary outlier) used throughout the notebook.

In [1]:
import pandas as pd
import numpy as np

# A simple sample Series
s = pd.Series([10, 20, 30, 40, 50])

# A deliberately messy sample DataFrame for cleaning/manipulation exercises
data = {
    "id": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "name": ["Alice", "Bob", "charlie", "DAVID", "Eve", "Frank", "Grace", "Heidi", "Ivan", "Alice"],
    "department": ["HR", "IT", "IT", "Finance", "HR", "IT", "Finance", "HR", "IT", "HR"],
    "age": [25, 30, 35, 28, np.nan, 40, 32, 29, 38, 25],
    "salary": [50000, 60000, 55000, 70000, 52000, 650000, 58000, 61000, 59000, 50000],  # 650000 is an outlier
    "city": [" Pune", "Mumbai ", "DELHI", "bangalore", "Pune", "Mumbai", "Delhi", "Bangalore", "Pune ", "Pune"],
    "email": ["alice@gmail.com", "bob@yahoo.com", "charlie@gmail.com", "david@gmail.com",
              "eve@yahoo.com", "frank@gmail.com", "grace@yahoo.com", "heidi@gmail.com",
              "ivan@yahoo.com", "alice@gmail.com"],
    "joining_date": pd.date_range("2018-01-01", periods=10, freq="6ME")
}
df = pd.DataFrame(data)
df

,id,name,department,age,salary,city,email,joining_date
0,1,Alice,HR,25.0,50000,Pune,alice@gmail.com,2018-01-31
1,2,Bob,IT,30.0,60000,Mumbai,bob@yahoo.com,2018-07-31
2,3,charlie,IT,35.0,55000,DELHI,charlie@gmail.com,2019-01-31
3,4,DAVID,Finance,28.0,70000,bangalore,david@gmail.com,2019-07-31
4,5,Eve,HR,NaN,52000,Pune,eve@yahoo.com,2020-01-31
5,6,Frank,IT,40.0,650000,Mumbai,frank@gmail.com,2020-07-31
6,7,Grace,Finance,32.0,58000,Delhi,grace@yahoo.com,2021-01-31
7,8,Heidi,HR,29.0,61000,Bangalore,heidi@gmail.com,2021-07-31
8,9,Ivan,IT,38.0,59000,Pune,ivan@yahoo.com,2022-01-31
9,10,Alice,HR,25.0,50000,Pune,alice@gmail.com,2022-07-31

## 🔹 Section 1: Basics & Series (Q1–Q20)

### Q1. Create a Pandas Series from a list of integers.
> 💡 **Hint:** Use `pd.Series([...])`. The default index starts from 0.

In [2]:
s1 = pd.Series([10, 20, 30, 40, 50])
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

### Q2. Create a Series from a dictionary with custom index.
> 💡 **Hint:** Pass a `dict` to `pd.Series()`. Keys become the index labels automatically.

In [3]:
s2 = pd.Series({"a": 100, "b": 200, "c": 300})
s2

a    100
b    200
c    300
dtype: int64

### Q3. Access elements using index labels.
> 💡 **Hint:** Use `s["label"]` for a single value, `s[["a","b"]]` for multiple, and `s["a":"c"]` for a range. Label slices are **inclusive** on both ends.

In [ ]:
print(s2["a"])          # single value
print(s2[["a", "b"]])   # multiple values
print(s2["a":"c"])      # range, inclusive of both ends

### Q4. Perform arithmetic operations on a Series.
> 💡 **Hint:** Use `+`, `-`, `*`, `/`, `//`, `%`, `**` directly on the Series. Operations are **element-wise** and **index-aligned**.

In [4]:
s3 = pd.Series([1, 2, 3, 4, 5])
print(s3 + 10)
print(s3 * 2)
print(s3 ** 2)

0    11
1    12
2    13
3    14
4    15
dtype: int64
0     2
1     4
2     6
3     8
4    10
dtype: int64
0     1
1     4
2     9
3    16
4    25
dtype: int64

### Q5. Find mean, min, max of a Series.
> 💡 **Hint:** Use `.mean()`, `.min()`, `.max()`, `.sum()`, `.median()`, `.std()` directly on the Series.

In [5]:
print("Mean:", s3.mean())
print("Min:", s3.min())
print("Max:", s3.max())
print("Sum:", s3.sum())
print("Median:", s3.median())
print("Std:", s3.std())

Mean: 3.0
Min: 1
Max: 5
Sum: 15
Median: 3.0
Std: 1.5811388300841898

### Q6. Apply conditional filtering on a Series.
> 💡 **Hint:** Use a boolean mask: `s[s > 50]`. You can also chain conditions with `&` and `|`.

In [6]:
s4 = pd.Series([10, 45, 60, 25, 80])
print(s4[s4 > 50])
print(s4[(s4 > 20) & (s4 < 70)])

2    60
4    80
dtype: int64
1    45
2    60
3    25
dtype: int64

### Q7. Replace values in a Series.
> 💡 **Hint:** Use `.replace(old_val, new_val)` or pass a dictionary `{old: new}` to replace multiple values at once.

In [7]:
s5 = pd.Series([1, 2, 3, 2, 1])
print(s5.replace(2, 200))
print(s5.replace({1: 100, 3: 300}))

0      1
1    200
2      3
3    200
4      1
dtype: int64
0    100
1      2
2    300
3      2
4    100
dtype: int64

### Q8. Convert Series data type.
> 💡 **Hint:** Use `.astype(dtype)` — e.g., `.astype(int)`, `.astype(float)`, `.astype("category")`.

In [8]:
s6 = pd.Series([1, 2, 3])
print(s6.astype(float))
print(s6.astype("category"))

0    1.0
1    2.0
2    3.0
dtype: float64
0    1
1    2
2    3
dtype: category
Categories (3, int64): [1, 2, 3]

### Q9. Check for null values in Series.
> 💡 **Hint:** Use `.isnull()` (returns boolean Series) or `.isnull().sum()` for a count.

In [9]:
s7 = pd.Series([1, np.nan, 3, None])
print(s7.isnull())
print("Null count:", s7.isnull().sum())

0    False
1     True
2    False
3     True
dtype: bool
Null count: 2

### Q10. Fill missing values in Series.
> 💡 **Hint:** Use `.fillna(value)` for constant, `.fillna(s.mean())` for mean, `.ffill()` for forward fill, `.bfill()` for backward fill.

In [10]:
print(s7.fillna(0))
print(s7.fillna(s7.mean()))
print(s7.ffill())
print(s7.bfill())

0    1.0
1    0.0
2    3.0
3    0.0
dtype: float64
0    1.0
1    2.0
2    3.0
3    2.0
dtype: float64
0    1.0
1    1.0
2    3.0
3    3.0
dtype: float64
0    1.0
1    3.0
2    3.0
3    NaN
dtype: float64

### Q11. Create DataFrame from a list.
> 💡 **Hint:** Use `pd.DataFrame(list_of_lists, columns=[...])`. Each inner list becomes one row.

In [11]:
df11 = pd.DataFrame([[1, "A"], [2, "B"], [3, "C"]], columns=["id", "letter"])
df11

   id letter
0   1      A
1   2      B
2   3      C

### Q12. Create DataFrame from a dictionary.
> 💡 **Hint:** Use `pd.DataFrame({col: values})`. Keys become column names; values must have equal length.

In [12]:
df12 = pd.DataFrame({"col1": [1, 2, 3], "col2": ["x", "y", "z"]})
df12

   col1 col2
0     1    x
1     2    y
2     3    z

### Q13. Create DataFrame from list of dictionaries.
> 💡 **Hint:** Use `pd.DataFrame([{...}, {...}])`. Each dict is a row; missing keys become `NaN`.

In [13]:
df13 = pd.DataFrame([{"a": 1, "b": 2}, {"a": 3, "c": 4}])
df13

   a    b    c
0  1  2.0  NaN
1  3  NaN  4.0

### Q14. Display DataFrame structure (shape, columns, dtypes).
> 💡 **Hint:** Use `df.shape`, `df.columns`, `df.dtypes`, `df.info()`, and `df.describe()`.

In [14]:
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
print("Dtypes:\n", df.dtypes)
df.info()

Shape: (10, 8)
Columns: ['id', 'name', 'department', 'age', 'salary', 'city', 'email', 'joining_date']
Dtypes:
 id                       int64
name                    object
department              object
age                    float64
salary                   int64
city                    object
email                   object
joining_date    datetime64[ns]
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            10 non-null     int64
 1   name          10 non-null     object
 2   department    10 non-null     object
 3   age           9 non-null      float64
 4   salary        10 non-null     int64
 5   city          10 non-null     object
 6   email         10 non-null     object
 7   joining_date  10 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(2), object(4)
memory usage: 772.0+ bytes

In [15]:
df.describe()

             id        age        salary         joining_date
count  10.00000   9.000000      10.00000                   10
mean    5.50000  31.333333  116500.00000  2020-05-01 00:00:00
min     1.00000  25.000000   50000.00000  2018-01-31 00:00:00
25%     3.25000  28.000000   52750.00000  2019-03-17 06:00:00
50%     5.50000  30.000000   58500.00000  2020-05-01 00:00:00
75%     7.75000  35.000000   60750.00000  2021-06-15 18:00:00
max    10.00000  40.000000  650000.00000  2022-07-31 00:00:00
std     3.02765   5.385165  187549.25279                  NaN

### Q15. Select single column from DataFrame.
> 💡 **Hint:** Use `df["col_name"]` — this returns a **Series**. You can also use `df.col_name` (dot notation).

In [16]:
df["name"]

0      Alice
1        Bob
2    charlie
3      DAVID
4        Eve
5      Frank
6      Grace
7      Heidi
8       Ivan
9      Alice
Name: name, dtype: object

### Q16. Select multiple columns.
> 💡 **Hint:** Use `df[["col1", "col2"]]` with a list inside the brackets — this returns a **DataFrame**.

In [18]:
df[["name", "department"]]

      name department
0    Alice         HR
1      Bob         IT
2  charlie         IT
3    DAVID    Finance
4      Eve         HR
5    Frank         IT
6    Grace    Finance
7    Heidi         HR
8     Ivan         IT
9    Alice         HR

### Q17. Add new column with scalar value.
> 💡 **Hint:** `df["new_col"] = 10` — the scalar is **broadcast** to all rows automatically.

In [19]:
df17 = df.copy()
df17["country"] = "India"
df17.head()

,id,name,department,age,salary,city,email,joining_date,country
0,1,Alice,HR,25.0,50000,Pune,alice@gmail.com,2018-01-31,India
1,2,Bob,IT,30.0,60000,Mumbai,bob@yahoo.com,2018-07-31,India
2,3,charlie,IT,35.0,55000,DELHI,charlie@gmail.com,2019-01-31,India
3,4,DAVID,Finance,28.0,70000,bangalore,david@gmail.com,2019-07-31,India
4,5,Eve,HR,NaN,52000,Pune,eve@yahoo.com,2020-01-31,India

### Q18. Add column using Series.
> 💡 **Hint:** `df["new_col"] = pd.Series([...])`. The Series index must align with the DataFrame index.

In [20]:
df18 = df.copy()
df18["bonus"] = pd.Series([1000] * len(df18))
df18.head()

,id,name,department,age,salary,city,email,joining_date,bonus
0,1,Alice,HR,25.0,50000,Pune,alice@gmail.com,2018-01-31,1000
1,2,Bob,IT,30.0,60000,Mumbai,bob@yahoo.com,2018-07-31,1000
2,3,charlie,IT,35.0,55000,DELHI,charlie@gmail.com,2019-01-31,1000
3,4,DAVID,Finance,28.0,70000,bangalore,david@gmail.com,2019-07-31,1000
4,5,Eve,HR,NaN,52000,Pune,eve@yahoo.com,2020-01-31,1000

### Q19. Rename columns using `rename()`.
> 💡 **Hint:** Use `df.rename(columns={"old": "new"})`. Add `inplace=True` to modify in-place.

In [21]:
df19 = df.rename(columns={"name": "employee_name"})
df19.head()

,id,employee_name,department,age,salary,city,email,joining_date
0,1,Alice,HR,25.0,50000,Pune,alice@gmail.com,2018-01-31
1,2,Bob,IT,30.0,60000,Mumbai,bob@yahoo.com,2018-07-31
2,3,charlie,IT,35.0,55000,DELHI,charlie@gmail.com,2019-01-31
3,4,DAVID,Finance,28.0,70000,bangalore,david@gmail.com,2019-07-31
4,5,Eve,HR,NaN,52000,Pune,eve@yahoo.com,2020-01-31

### Q20. Rename multiple columns.
> 💡 **Hint:** Pass a dictionary with multiple key-value pairs to `rename(columns={...})`.

In [22]:
df20 = df.rename(columns={"name": "employee_name", "age": "employee_age"})
df20.head()

,id,employee_name,department,employee_age,salary,city,email,joining_date
0,1,Alice,HR,25.0,50000,Pune,alice@gmail.com,2018-01-31
1,2,Bob,IT,30.0,60000,Mumbai,bob@yahoo.com,2018-07-31
2,3,charlie,IT,35.0,55000,DELHI,charlie@gmail.com,2019-01-31
3,4,DAVID,Finance,28.0,70000,bangalore,david@gmail.com,2019-07-31
4,5,Eve,HR,NaN,52000,Pune,eve@yahoo.com,2020-01-31

## 🔹 Section 2: Indexing, Selection & Slicing (Q21–Q40)

### Q21. Select rows using `loc`.
> 💡 **Hint:** `df.loc[label]` for a single row, `df.loc[label1:label2]` for a range. **Inclusive on both ends.**

In [23]:
print(df.loc[0])
df.loc[0:3]

id                                1
name                          Alice
department                       HR
age                            25.0
salary                        50000
city                           Pune
email               alice@gmail.com
joining_date    2018-01-31 00:00:00
Name: 0, dtype: object

,id,name,department,age,salary,city,email,joining_date
0,1,Alice,HR,25.0,50000,Pune,alice@gmail.com,2018-01-31
1,2,Bob,IT,30.0,60000,Mumbai,bob@yahoo.com,2018-07-31
2,3,charlie,IT,35.0,55000,DELHI,charlie@gmail.com,2019-01-31
3,4,DAVID,Finance,28.0,70000,bangalore,david@gmail.com,2019-07-31

### Q22. Select rows using `iloc`.
> 💡 **Hint:** `df.iloc[0]` for first row, `df.iloc[1:4]` for rows 1–3. **Exclusive on the end** (Python-style).

In [24]:
print(df.iloc[0])
df.iloc[1:4]

id                                1
name                          Alice
department                       HR
age                            25.0
salary                        50000
city                           Pune
email               alice@gmail.com
joining_date    2018-01-31 00:00:00
Name: 0, dtype: object

,id,name,department,age,salary,city,email,joining_date
1,2,Bob,IT,30.0,60000,Mumbai,bob@yahoo.com,2018-07-31
2,3,charlie,IT,35.0,55000,DELHI,charlie@gmail.com,2019-01-31
3,4,DAVID,Finance,28.0,70000,bangalore,david@gmail.com,2019-07-31

### Q23. Access specific row and column.
> 💡 **Hint:** `df.loc[row_label, "col_name"]` or `df.iloc[row_pos, col_pos]` for a single cell.

In [25]:
print(df.loc[0, "name"])
print(df.iloc[0, 1])

Alice
Alice

### Q24. Select subset using multiple rows & columns.
> 💡 **Hint:** `df.loc[[r1,r2], ["col1","col2"]]` or `df.iloc[[0,1], [0,2]]`.

In [26]:
print(df.loc[[0, 1], ["name", "salary"]])
print(df.iloc[[0, 1], [1, 4]])

    name  salary
0  Alice   50000
1    Bob   60000
    name  salary
0  Alice   50000
1    Bob   60000

### Q25. Apply conditional filtering using `loc`.
> 💡 **Hint:** `df.loc[df["col"] > value, ["col1","col2"]]` — pass a boolean Series as the row selector.

In [27]:
df.loc[df["salary"] > 60000, ["name", "salary"]]

    name  salary
3  DAVID   70000
5  Frank  650000
7  Heidi   61000

### Q26. Slice rows using index range.
> 💡 **Hint:** Use `df.iloc[start:end]` for position-based slicing or `df.loc[label1:label2]` for label-based slicing.

In [28]:
df.iloc[2:6]

,id,name,department,age,salary,city,email,joining_date
2,3,charlie,IT,35.0,55000,DELHI,charlie@gmail.com,2019-01-31
3,4,DAVID,Finance,28.0,70000,bangalore,david@gmail.com,2019-07-31
4,5,Eve,HR,NaN,52000,Pune,eve@yahoo.com,2020-01-31
5,6,Frank,IT,40.0,650000,Mumbai,frank@gmail.com,2020-07-31

### Q27. Slice columns using labels.
> 💡 **Hint:** `df.loc[:, "col1":"col3"]` — selects all rows, columns from col1 to col3 (label-inclusive).

In [30]:
df

,id,name,department,age,salary,city,email,joining_date
0,1,Alice,HR,25.0,50000,Pune,alice@gmail.com,2018-01-31
1,2,Bob,IT,30.0,60000,Mumbai,bob@yahoo.com,2018-07-31
2,3,charlie,IT,35.0,55000,DELHI,charlie@gmail.com,2019-01-31
3,4,DAVID,Finance,28.0,70000,bangalore,david@gmail.com,2019-07-31
4,5,Eve,HR,NaN,52000,Pune,eve@yahoo.com,2020-01-31
5,6,Frank,IT,40.0,650000,Mumbai,frank@gmail.com,2020-07-31
6,7,Grace,Finance,32.0,58000,Delhi,grace@yahoo.com,2021-01-31
7,8,Heidi,HR,29.0,61000,Bangalore,heidi@gmail.com,2021-07-31
8,9,Ivan,IT,38.0,59000,Pune,ivan@yahoo.com,2022-01-31
9,10,Alice,HR,25.0,50000,Pune,alice@gmail.com,2022-07-31

In [29]:
df.loc[:, "name":"age"]

      name department   age
0    Alice         HR  25.0
1      Bob         IT  30.0
2  charlie         IT  35.0
3    DAVID    Finance  28.0
4      Eve         HR   NaN
5    Frank         IT  40.0
6    Grace    Finance  32.0
7    Heidi         HR  29.0
8     Ivan         IT  38.0
9    Alice         HR  25.0

### Q28. Slice columns using position.
> 💡 **Hint:** `df.iloc[:, 1:4]` — selects all rows, columns at positions 1, 2, 3.

In [31]:
df.iloc[:, 1:4]

      name department   age
0    Alice         HR  25.0
1      Bob         IT  30.0
2  charlie         IT  35.0
3    DAVID    Finance  28.0
4      Eve         HR   NaN
5    Frank         IT  40.0
6    Grace    Finance  32.0
7    Heidi         HR  29.0
8     Ivan         IT  38.0
9    Alice         HR  25.0

### Q29. Perform combined row & column slicing.
> 💡 **Hint:** `df.loc[row_condition, ["col1","col2"]]` or `df.iloc[0:5, [0, 2, 4]]`.

In [32]:
print(df.loc[df["department"] == "IT", ["name", "salary"]])
print(df.iloc[0:5, [0, 2, 4]])

      name  salary
1      Bob   60000
2  charlie   55000
5    Frank  650000
8     Ivan   59000
   id department  salary
0   1         HR   50000
1   2         IT   60000
2   3         IT   55000
3   4    Finance   70000
4   5         HR   52000

### Q30. Set a column as index.
> 💡 **Hint:** Use `df.set_index("col_name")`. Add `inplace=True` to modify without reassigning.

In [33]:
df30 = df.set_index("id")
df30.head()

,name,department,age,salary,city,email,joining_date
id,,,,,,,
1,Alice,HR,25.0,50000,Pune,alice@gmail.com,2018-01-31
2,Bob,IT,30.0,60000,Mumbai,bob@yahoo.com,2018-07-31
3,charlie,IT,35.0,55000,DELHI,charlie@gmail.com,2019-01-31
4,DAVID,Finance,28.0,70000,bangalore,david@gmail.com,2019-07-31
5,Eve,HR,NaN,52000,Pune,eve@yahoo.com,2020-01-31

### Q31. Create hierarchical index (MultiIndex).
> 💡 **Hint:** `df.set_index(["col1","col2"])` — pass a **list** of column names to create a MultiIndex.

In [ ]:
df31 = df.set_index(["department", "id"])
df31.head()

### Q32. Reset index.
> 💡 **Hint:** `df.reset_index()` — moves the current index back to a column. Use `inplace=True` to modify in-place.

In [34]:
df30.reset_index().head()

,id,name,department,age,salary,city,email,joining_date
0,1,Alice,HR,25.0,50000,Pune,alice@gmail.com,2018-01-31
1,2,Bob,IT,30.0,60000,Mumbai,bob@yahoo.com,2018-07-31
2,3,charlie,IT,35.0,55000,DELHI,charlie@gmail.com,2019-01-31
3,4,DAVID,Finance,28.0,70000,bangalore,david@gmail.com,2019-07-31
4,5,Eve,HR,NaN,52000,Pune,eve@yahoo.com,2020-01-31

### Q33. Reset multi-index.
> 💡 **Hint:** `df.reset_index()` on a MultiIndex DataFrame flattens both index levels back to columns.

In [35]:
df31.reset_index().head()

NameError: name 'df31' is not defined

### Q34. Convert index to column.
> 💡 **Hint:** `df.reset_index()` by default moves the index to a column. Use `drop=False` (default) to keep it.

In [36]:
df34 = df.set_index("id")
df34.reset_index(drop=False).head()

,id,name,department,age,salary,city,email,joining_date
0,1,Alice,HR,25.0,50000,Pune,alice@gmail.com,2018-01-31
1,2,Bob,IT,30.0,60000,Mumbai,bob@yahoo.com,2018-07-31
2,3,charlie,IT,35.0,55000,DELHI,charlie@gmail.com,2019-01-31
3,4,DAVID,Finance,28.0,70000,bangalore,david@gmail.com,2019-07-31
4,5,Eve,HR,NaN,52000,Pune,eve@yahoo.com,2020-01-31

### Q35. Use drop option in `reset_index`.
> 💡 **Hint:** `df.reset_index(drop=True)` discards the old index completely instead of converting it to a column.

In [37]:
df.set_index("id").reset_index(drop=True).head()

      name department   age  salary       city              email joining_date
0    Alice         HR  25.0   50000       Pune    alice@gmail.com   2018-01-31
1      Bob         IT  30.0   60000    Mumbai       bob@yahoo.com   2018-07-31
2  charlie         IT  35.0   55000      DELHI  charlie@gmail.com   2019-01-31
3    DAVID    Finance  28.0   70000  bangalore    david@gmail.com   2019-07-31
4      Eve         HR   NaN   52000       Pune      eve@yahoo.com   2020-01-31

### Q36. Perform label-based indexing.
> 💡 **Hint:** Use `df.loc[label]` — works with any index type (string, integer, datetime labels).

In [38]:
df.loc[3]

id                                4
name                          DAVID
department                  Finance
age                            28.0
salary                        70000
city                      bangalore
email               david@gmail.com
joining_date    2019-07-31 00:00:00
Name: 3, dtype: object

### Q37. Perform position-based indexing.
> 💡 **Hint:** Use `df.iloc[0]` — always integer-based, regardless of the index type.

In [39]:
df.iloc[3]

id                                4
name                          DAVID
department                  Finance
age                            28.0
salary                        70000
city                      bangalore
email               david@gmail.com
joining_date    2019-07-31 00:00:00
Name: 3, dtype: object

### Q38. Access first N rows.
> 💡 **Hint:** `df.head(N)` — default N is 5.

In [ ]:
df.head(3)

### Q39. Access last N rows.
> 💡 **Hint:** `df.tail(N)` — default N is 5.

In [42]:
df.tail(3)

   id   name department   age  salary       city            email joining_date
7   8  Heidi         HR  29.0   61000  Bangalore  heidi@gmail.com   2021-07-31
8   9   Ivan         IT  38.0   59000      Pune    ivan@yahoo.com   2022-01-31
9  10  Alice         HR  25.0   50000       Pune  alice@gmail.com   2022-07-31

### Q40. Extract random sample from DataFrame.
> 💡 **Hint:** `df.sample(n=5)` for random rows, `df.sample(frac=0.2)` for 20% of rows. Set `random_state` for reproducibility.

In [43]:
df.sample(n=3, random_state=42)

   id   name department   age  salary     city            email joining_date
8   9   Ivan         IT  38.0   59000    Pune    ivan@yahoo.com   2022-01-31
1   2    Bob         IT  30.0   60000  Mumbai     bob@yahoo.com   2018-07-31
5   6  Frank         IT  40.0  650000   Mumbai  frank@gmail.com   2020-07-31

## 🔹 Section 3: Data Cleaning (Q41–Q60)

### Q41. Detect missing values using `isnull()`.
> 💡 **Hint:** `df.isnull()` returns a boolean DataFrame. Use `.isnull().sum()` for column-wise counts or `.isnull().any()` to check if any exist.

In [45]:
df

,id,name,department,age,salary,city,email,joining_date
0,1,Alice,HR,25.0,50000,Pune,alice@gmail.com,2018-01-31
1,2,Bob,IT,30.0,60000,Mumbai,bob@yahoo.com,2018-07-31
2,3,charlie,IT,35.0,55000,DELHI,charlie@gmail.com,2019-01-31
3,4,DAVID,Finance,28.0,70000,bangalore,david@gmail.com,2019-07-31
4,5,Eve,HR,NaN,52000,Pune,eve@yahoo.com,2020-01-31
5,6,Frank,IT,40.0,650000,Mumbai,frank@gmail.com,2020-07-31
6,7,Grace,Finance,32.0,58000,Delhi,grace@yahoo.com,2021-01-31
7,8,Heidi,HR,29.0,61000,Bangalore,heidi@gmail.com,2021-07-31
8,9,Ivan,IT,38.0,59000,Pune,ivan@yahoo.com,2022-01-31
9,10,Alice,HR,25.0,50000,Pune,alice@gmail.com,2022-07-31

In [44]:
print(df.isnull().sum())
print(df.isnull().any())

id              0
name            0
department      0
age             1
salary          0
city            0
email           0
joining_date    0
dtype: int64
id              False
name            False
department      False
age              True
salary          False
city            False
email           False
joining_date    False
dtype: bool

### Q42. Drop missing values using `dropna()`.
> 💡 **Hint:** `df.dropna()` drops any row with a NaN. Use `axis=1` for columns, `subset=["col"]` for specific columns, and `thresh=N` to keep rows with at least N non-null values.

In [46]:
print(df.dropna().shape)
df.dropna(subset=["age"])

(9, 8)

,id,name,department,age,salary,city,email,joining_date
0,1,Alice,HR,25.0,50000,Pune,alice@gmail.com,2018-01-31
1,2,Bob,IT,30.0,60000,Mumbai,bob@yahoo.com,2018-07-31
2,3,charlie,IT,35.0,55000,DELHI,charlie@gmail.com,2019-01-31
3,4,DAVID,Finance,28.0,70000,bangalore,david@gmail.com,2019-07-31
5,6,Frank,IT,40.0,650000,Mumbai,frank@gmail.com,2020-07-31
6,7,Grace,Finance,32.0,58000,Delhi,grace@yahoo.com,2021-01-31
7,8,Heidi,HR,29.0,61000,Bangalore,heidi@gmail.com,2021-07-31
8,9,Ivan,IT,38.0,59000,Pune,ivan@yahoo.com,2022-01-31
9,10,Alice,HR,25.0,50000,Pune,alice@gmail.com,2022-07-31

### Q43. Fill missing values with a constant.
> 💡 **Hint:** `df.fillna(0)` or `df["col"].fillna("Unknown")`. You can also pass a dict to fill different columns with different values.

In [48]:
print(df["age"].fillna(0))
df.fillna({"age": 0})

0    25.0
1    30.0
2    35.0
3    28.0
4     0.0
5    40.0
6    32.0
7    29.0
8    38.0
9    25.0
Name: age, dtype: float64

,id,name,department,age,salary,city,email,joining_date
0,1,Alice,HR,25.0,50000,Pune,alice@gmail.com,2018-01-31
1,2,Bob,IT,30.0,60000,Mumbai,bob@yahoo.com,2018-07-31
2,3,charlie,IT,35.0,55000,DELHI,charlie@gmail.com,2019-01-31
3,4,DAVID,Finance,28.0,70000,bangalore,david@gmail.com,2019-07-31
4,5,Eve,HR,0.0,52000,Pune,eve@yahoo.com,2020-01-31
5,6,Frank,IT,40.0,650000,Mumbai,frank@gmail.com,2020-07-31
6,7,Grace,Finance,32.0,58000,Delhi,grace@yahoo.com,2021-01-31
7,8,Heidi,HR,29.0,61000,Bangalore,heidi@gmail.com,2021-07-31
8,9,Ivan,IT,38.0,59000,Pune,ivan@yahoo.com,2022-01-31
9,10,Alice,HR,25.0,50000,Pune,alice@gmail.com,2022-07-31

### Q44. Fill missing values using mean/median.
> 💡 **Hint:** `df["col"].fillna(df["col"].mean())` or `df["col"].fillna(df["col"].median())`.

In [49]:
print(df["age"].fillna(df["age"].mean()))
print(df["age"].fillna(df["age"].median()))

0    25.000000
1    30.000000
2    35.000000
3    28.000000
4    31.333333
5    40.000000
6    32.000000
7    29.000000
8    38.000000
9    25.000000
Name: age, dtype: float64
0    25.0
1    30.0
2    35.0
3    28.0
4    30.0
5    40.0
6    32.0
7    29.0
8    38.0
9    25.0
Name: age, dtype: float64

### Q45. Use forward fill and backward fill.
> 💡 **Hint:** `df.ffill()` propagates the last valid value forward. `df.bfill()` fills using the next valid value.

In [50]:
print(df["age"].ffill())
print(df["age"].bfill())

0    25.0
1    30.0
2    35.0
3    28.0
4    28.0
5    40.0
6    32.0
7    29.0
8    38.0
9    25.0
Name: age, dtype: float64
0    25.0
1    30.0
2    35.0
3    28.0
4    40.0
5    40.0
6    32.0
7    29.0
8    38.0
9    25.0
Name: age, dtype: float64

### Q46. Convert data type using `astype()`.
> 💡 **Hint:** `df["col"].astype(int)` or `df["col"].astype("category")`. Use `errors="coerce"` inside `pd.to_numeric()` to handle invalid values.

In [ ]:
df46 = df.copy()
df46["age"] = df46["age"].fillna(0).astype(int)
df46["department"] = df46["department"].astype("category")
df46.dtypes

### Q47. Clean string column using `.str.lower()`.
> 💡 **Hint:** Access the `.str` accessor first: `df["col"].str.lower()`. Similarly `.str.upper()`, `.str.title()`.

In [51]:
print(df["city"].str.lower())
print(df["city"].str.title())

0         pune
1      mumbai
2        delhi
3    bangalore
4         pune
5       mumbai
6        delhi
7    bangalore
8        pune
9         pune
Name: city, dtype: object
0         Pune
1      Mumbai
2        Delhi
3    Bangalore
4         Pune
5       Mumbai
6        Delhi
7    Bangalore
8        Pune
9         Pune
Name: city, dtype: object

### Q48. Trim whitespace in strings.
> 💡 **Hint:** `df["col"].str.strip()` removes leading and trailing spaces. Use `.str.lstrip()` / `.str.rstrip()` for one side.

In [52]:
df["city"].str.strip()

0         Pune
1       Mumbai
2        DELHI
3    bangalore
4         Pune
5       Mumbai
6        Delhi
7    Bangalore
8         Pune
9         Pune
Name: city, dtype: object

### Q49. Replace substring in column.
> 💡 **Hint:** `df["col"].str.replace("old", "new")`. Add `regex=True` for pattern-based replacement.

In [53]:
df["department"].str.replace("IT", "Information Technology")

0                        HR
1    Information Technology
2    Information Technology
3                   Finance
4                        HR
5    Information Technology
6                   Finance
7                        HR
8    Information Technology
9                        HR
Name: department, dtype: object

### Q50. Extract part of string using `.str`.
> 💡 **Hint:** `df["col"].str[:3]` for first 3 chars. Use `.str.split("@").str[1]` to extract after a delimiter.

In [54]:
print(df["email"].str[:5])
print(df["email"].str.split("@").str[1])

0    alice
1    bob@y
2    charl
3    david
4    eve@y
5    frank
6    grace
7    heidi
8    ivan@
9    alice
Name: email, dtype: object
0    gmail.com
1    yahoo.com
2    gmail.com
3    gmail.com
4    yahoo.com
5    gmail.com
6    yahoo.com
7    gmail.com
8    yahoo.com
9    gmail.com
Name: email, dtype: object

### Q51. Detect duplicate rows.
> 💡 **Hint:** `df.duplicated()` returns a boolean Series. Use `df[df.duplicated()]` to see the actual duplicate rows.

In [55]:
print(df.duplicated())
df[df.duplicated()]

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

Empty DataFrame
Columns: [id, name, department, age, salary, city, email, joining_date]
Index: []

### Q52. Remove duplicates using `drop_duplicates()`.
> 💡 **Hint:** `df.drop_duplicates()` keeps the first occurrence by default. Use `subset=["col"]` to check specific columns, and `keep="last"` or `keep=False`.

In [56]:
df.drop_duplicates(subset=["name"], keep="first")

,id,name,department,age,salary,city,email,joining_date
0,1,Alice,HR,25.0,50000,Pune,alice@gmail.com,2018-01-31
1,2,Bob,IT,30.0,60000,Mumbai,bob@yahoo.com,2018-07-31
2,3,charlie,IT,35.0,55000,DELHI,charlie@gmail.com,2019-01-31
3,4,DAVID,Finance,28.0,70000,bangalore,david@gmail.com,2019-07-31
4,5,Eve,HR,NaN,52000,Pune,eve@yahoo.com,2020-01-31
5,6,Frank,IT,40.0,650000,Mumbai,frank@gmail.com,2020-07-31
6,7,Grace,Finance,32.0,58000,Delhi,grace@yahoo.com,2021-01-31
7,8,Heidi,HR,29.0,61000,Bangalore,heidi@gmail.com,2021-07-31
8,9,Ivan,IT,38.0,59000,Pune,ivan@yahoo.com,2022-01-31

### Q53. Rename row labels.
> 💡 **Hint:** `df.rename(index={old_label: new_label})`.

In [58]:
df.rename(index={0: "first_row", 1: "second_row"}).head()

,id,name,department,age,salary,city,email,joining_date
first_row,1,Alice,HR,25.0,50000,Pune,alice@gmail.com,2018-01-31
second_row,2,Bob,IT,30.0,60000,Mumbai,bob@yahoo.com,2018-07-31
2,3,charlie,IT,35.0,55000,DELHI,charlie@gmail.com,2019-01-31
3,4,DAVID,Finance,28.0,70000,bangalore,david@gmail.com,2019-07-31
4,5,Eve,HR,NaN,52000,Pune,eve@yahoo.com,2020-01-31

### Q54. Handle inconsistent data.
> 💡 **Hint:** Use `.str.strip().str.lower()` to normalize strings. Use `.replace({...})` to map inconsistent values to a standard form.

In [57]:
df54 = df.copy()
df54["city_clean"] = df54["city"].str.strip().str.lower()
df54[["city", "city_clean"]]

        city city_clean
0       Pune       pune
1    Mumbai      mumbai
2      DELHI      delhi
3  bangalore  bangalore
4       Pune       pune
5     Mumbai     mumbai
6      Delhi      delhi
7  Bangalore  bangalore
8      Pune        pune
9       Pune       pune

### Q55. Replace values in DataFrame.
> 💡 **Hint:** `df.replace("old", "new")` works DataFrame-wide. Pass a dict `{old: new}` or nested dict `{"col": {old: new}}` for column-specific replacement.

In [59]:
df.replace({"department": {"IT": "Information Technology"}})

,id,name,department,age,salary,city,email,joining_date
0,1,Alice,HR,25.0,50000,Pune,alice@gmail.com,2018-01-31
1,2,Bob,Information Technology,30.0,60000,Mumbai,bob@yahoo.com,2018-07-31
2,3,charlie,Information Technology,35.0,55000,DELHI,charlie@gmail.com,2019-01-31
3,4,DAVID,Finance,28.0,70000,bangalore,david@gmail.com,2019-07-31
4,5,Eve,HR,NaN,52000,Pune,eve@yahoo.com,2020-01-31
5,6,Frank,Information Technology,40.0,650000,Mumbai,frank@gmail.com,2020-07-31
6,7,Grace,Finance,32.0,58000,Delhi,grace@yahoo.com,2021-01-31
7,8,Heidi,HR,29.0,61000,Bangalore,heidi@gmail.com,2021-07-31
8,9,Ivan,Information Technology,38.0,59000,Pune,ivan@yahoo.com,2022-01-31
9,10,Alice,HR,25.0,50000,Pune,alice@gmail.com,2022-07-31

### Q56. Detect outliers in a column.
> 💡 **Hint:** Use the **IQR method**: compute Q1, Q3, IQR = Q3–Q1. Outliers are values below `Q1 - 1.5*IQR` or above `Q3 + 1.5*IQR`. Alternatively use Z-score: `|z| > 3`.

In [60]:
Q1 = df["salary"].quantile(0.25)
Q3 = df["salary"].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[(df["salary"] < lower_bound) | (df["salary"] > upper_bound)]
outliers

   id   name department   age  salary    city            email joining_date
5   6  Frank         IT  40.0  650000  Mumbai  frank@gmail.com   2020-07-31

### Q57. Handle outliers using clipping.
> 💡 **Hint:** `df["col"].clip(lower=lo, upper=hi)` replaces values outside the bounds with the boundary values.

In [61]:
df["salary"].clip(lower=lower_bound, upper=upper_bound)

0    50000
1    60000
2    55000
3    70000
4    52000
5    72750
6    58000
7    61000
8    59000
9    50000
Name: salary, dtype: int64

### Q58. Standardize column names.
> 💡 **Hint:** `df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")` — clean all column names in one line.

In [62]:
df58 = df.copy()
df58.columns = df58.columns.str.strip().str.lower().str.replace(" ", "_")
df58.columns.tolist()

['id', 'name', 'department', 'age', 'salary', 'city', 'email', 'joining_date']

### Q59. Handle mixed data types in a column.
> 💡 **Hint:** Use `pd.to_numeric(df["col"], errors="coerce")` to convert to numbers, turning invalid strings into `NaN`.

In [63]:
mixed = pd.Series(["1", "2", "abc", "4"])
pd.to_numeric(mixed, errors="coerce")

0    1.0
1    2.0
2    NaN
3    4.0
dtype: float64

### Q60. Remove special characters from text data.
> 💡 **Hint:** `df["col"].str.replace(r"[^a-zA-Z0-9 ]", "", regex=True)` — use regex to keep only alphanumeric characters.

In [64]:
messy_text = pd.Series(["Hello@World!", "Pandas#101", "Data$Science%"])
messy_text.str.replace(r"[^a-zA-Z0-9 ]", "", regex=True)

0     HelloWorld
1      Pandas101
2    DataScience
dtype: object

## 🔹 Section 4: Data Manipulation (Q61–Q80)

### Q61. Filter rows using AND condition.
> 💡 **Hint:** `df[(df["col1"] > val) & (df["col2"] == "x")]` — wrap each condition in parentheses and use `&`.

In [65]:
df[(df["department"] == "IT") & (df["salary"] > 55000)]

   id   name department   age  salary     city            email joining_date
1   2    Bob         IT  30.0   60000  Mumbai     bob@yahoo.com   2018-07-31
5   6  Frank         IT  40.0  650000   Mumbai  frank@gmail.com   2020-07-31
8   9   Ivan         IT  38.0   59000    Pune    ivan@yahoo.com   2022-01-31

### Q62. Filter rows using OR condition.
> 💡 **Hint:** `df[(df["col1"] > val) | (df["col2"] == "x")]` — use `|` between conditions.

In [66]:
df[(df["department"] == "HR") | (df["salary"] > 60000)]

   id   name department   age  salary       city            email joining_date
0   1  Alice         HR  25.0   50000       Pune  alice@gmail.com   2018-01-31
3   4  DAVID    Finance  28.0   70000  bangalore  david@gmail.com   2019-07-31
4   5    Eve         HR   NaN   52000       Pune    eve@yahoo.com   2020-01-31
5   6  Frank         IT  40.0  650000     Mumbai  frank@gmail.com   2020-07-31
7   8  Heidi         HR  29.0   61000  Bangalore  heidi@gmail.com   2021-07-31
9  10  Alice         HR  25.0   50000       Pune  alice@gmail.com   2022-07-31

### Q63. Filter rows using NOT condition.
> 💡 **Hint:** `df[~(df["col"] == "val")]` — use `~` to negate a boolean condition.

In [67]:
df[~(df["department"] == "IT")]

   id   name department   age  salary       city            email joining_date
0   1  Alice         HR  25.0   50000       Pune  alice@gmail.com   2018-01-31
3   4  DAVID    Finance  28.0   70000  bangalore  david@gmail.com   2019-07-31
4   5    Eve         HR   NaN   52000       Pune    eve@yahoo.com   2020-01-31
6   7  Grace    Finance  32.0   58000      Delhi  grace@yahoo.com   2021-01-31
7   8  Heidi         HR  29.0   61000  Bangalore  heidi@gmail.com   2021-07-31
9  10  Alice         HR  25.0   50000       Pune  alice@gmail.com   2022-07-31

### Q64. Sort DataFrame by column values.
> 💡 **Hint:** `df.sort_values("col")`. Use `ascending=False` for descending, `by=["col1","col2"]` for multi-column sort.

In [81]:
df.sort_values("salary", ascending=False)

,id,name,department,age,salary,city,email,joining_date
5,6,Frank,IT,40.0,650000,Mumbai,frank@gmail.com,2020-07-31
3,4,DAVID,Finance,28.0,70000,bangalore,david@gmail.com,2019-07-31
7,8,Heidi,HR,29.0,61000,Bangalore,heidi@gmail.com,2021-07-31
1,2,Bob,IT,30.0,60000,Mumbai,bob@yahoo.com,2018-07-31
8,9,Ivan,IT,38.0,59000,Pune,ivan@yahoo.com,2022-01-31
6,7,Grace,Finance,32.0,58000,Delhi,grace@yahoo.com,2021-01-31
2,3,charlie,IT,35.0,55000,DELHI,charlie@gmail.com,2019-01-31
4,5,Eve,HR,NaN,52000,Pune,eve@yahoo.com,2020-01-31
0,1,Alice,HR,25.0,50000,Pune,alice@gmail.com,2018-01-31
9,10,Alice,HR,25.0,50000,Pune,alice@gmail.com,2022-07-31

### Q65. Sort DataFrame by index.
> 💡 **Hint:** `df.sort_index()`. Use `axis=1` to sort columns alphabetically.

In [69]:
print(df.sort_index(ascending=False).head())
df.sort_index(axis=1).head()

   id   name department   age  salary       city            email joining_date
9  10  Alice         HR  25.0   50000       Pune  alice@gmail.com   2022-07-31
8   9   Ivan         IT  38.0   59000      Pune    ivan@yahoo.com   2022-01-31
7   8  Heidi         HR  29.0   61000  Bangalore  heidi@gmail.com   2021-07-31
6   7  Grace    Finance  32.0   58000      Delhi  grace@yahoo.com   2021-01-31
5   6  Frank         IT  40.0  650000     Mumbai  frank@gmail.com   2020-07-31

,age,city,department,email,id,joining_date,name,salary
0,25.0,Pune,HR,alice@gmail.com,1,2018-01-31,Alice,50000
1,30.0,Mumbai,IT,bob@yahoo.com,2,2018-07-31,Bob,60000
2,35.0,DELHI,IT,charlie@gmail.com,3,2019-01-31,charlie,55000
3,28.0,bangalore,Finance,david@gmail.com,4,2019-07-31,DAVID,70000
4,NaN,Pune,HR,eve@yahoo.com,5,2020-01-31,Eve,52000

### Q66. Add calculated column.
> 💡 **Hint:** `df["new"] = df["col1"] * df["col2"]` or use `.assign(new=lambda x: ...)` for chainable operations.

In [70]:
df66 = df.copy()
df66["annual_bonus"] = df66["salary"] * 0.10
df66[["name", "salary", "annual_bonus"]]

      name  salary  annual_bonus
0    Alice   50000        5000.0
1      Bob   60000        6000.0
2  charlie   55000        5500.0
3    DAVID   70000        7000.0
4      Eve   52000        5200.0
5    Frank  650000       65000.0
6    Grace   58000        5800.0
7    Heidi   61000        6100.0
8     Ivan   59000        5900.0
9    Alice   50000        5000.0

### Q67. Remove column using `drop()`.
> 💡 **Hint:** `df.drop(columns=["col1","col2"])`. Always use the `columns=` parameter to be explicit.

In [71]:
df.drop(columns=["email"]).head()

   id     name department   age  salary       city joining_date
0   1    Alice         HR  25.0   50000       Pune   2018-01-31
1   2      Bob         IT  30.0   60000    Mumbai    2018-07-31
2   3  charlie         IT  35.0   55000      DELHI   2019-01-31
3   4    DAVID    Finance  28.0   70000  bangalore   2019-07-31
4   5      Eve         HR   NaN   52000       Pune   2020-01-31

### Q68. Remove rows using `drop()`.
> 💡 **Hint:** `df.drop(index=[0, 3])` removes rows with those index labels.

In [72]:
df.drop(index=[0, 3])

,id,name,department,age,salary,city,email,joining_date
1,2,Bob,IT,30.0,60000,Mumbai,bob@yahoo.com,2018-07-31
2,3,charlie,IT,35.0,55000,DELHI,charlie@gmail.com,2019-01-31
4,5,Eve,HR,NaN,52000,Pune,eve@yahoo.com,2020-01-31
5,6,Frank,IT,40.0,650000,Mumbai,frank@gmail.com,2020-07-31
6,7,Grace,Finance,32.0,58000,Delhi,grace@yahoo.com,2021-01-31
7,8,Heidi,HR,29.0,61000,Bangalore,heidi@gmail.com,2021-07-31
8,9,Ivan,IT,38.0,59000,Pune,ivan@yahoo.com,2022-01-31
9,10,Alice,HR,25.0,50000,Pune,alice@gmail.com,2022-07-31

### Q69. Use `map()` on a column.
> 💡 **Hint:** `df["col"].map({"a": 1, "b": 2})` substitutes values using a dict. Pass a function for element-wise transformation.

In [73]:
df["department"].map({"HR": "Human Resources", "IT": "Information Technology", "Finance": "Finance"})

0           Human Resources
1    Information Technology
2    Information Technology
3                   Finance
4           Human Resources
5    Information Technology
6                   Finance
7           Human Resources
8    Information Technology
9           Human Resources
Name: department, dtype: object

### Q70. Apply function using `apply()`.
> 💡 **Hint:** `df["col"].apply(func)` for a Series. `df.apply(func, axis=0)` column-wise, `df.apply(func, axis=1)` row-wise.

In [74]:
print(df["salary"].apply(lambda x: x * 1.10))
df.apply(lambda row: row["salary"] / row["age"] if pd.notnull(row["age"]) and row["age"] != 0 else None, axis=1)

0     55000.0
1     66000.0
2     60500.0
3     77000.0
4     57200.0
5    715000.0
6     63800.0
7     67100.0
8     64900.0
9     55000.0
Name: salary, dtype: float64

0     2000.000000
1     2000.000000
2     1571.428571
3     2500.000000
4             NaN
5    16250.000000
6     1812.500000
7     2103.448276
8     1552.631579
9     2000.000000
dtype: float64

### Q71. Apply element-wise using `applymap()` / `map()`.
> 💡 **Hint:** In older pandas use `df.applymap(func)`. In pandas ≥ 2.1 use `df.map(func)` for element-wise operations on the entire DataFrame.

In [75]:
numeric_df = df[["age", "salary"]].fillna(0)
numeric_df.map(lambda x: x * 2)

    age   salary
0  50.0   100000
1  60.0   120000
2  70.0   110000
3  56.0   140000
4   0.0   104000
5  80.0  1300000
6  64.0   116000
7  58.0   122000
8  76.0   118000
9  50.0   100000

### Q72. Chain multiple operations.
> 💡 **Hint:** Use method chaining with `(df.copy().loc[...].sort_values(...)[cols].assign(...).reset_index(drop=True))` — wrap in parentheses for multi-line readability.

In [84]:
(
    df.copy()
      .dropna(subset=["age"])
      .sort_values("salary", ascending=False)[["name", "department", "salary"]]
      .reset_index(drop=True)
)

      name department  salary
0    Frank         IT  650000
1    DAVID    Finance   70000
2    Heidi         HR   61000
3      Bob         IT   60000
4     Ivan         IT   59000
5    Grace    Finance   58000
6  charlie         IT   55000
7    Alice         HR   50000
8    Alice         HR   50000

### Q73. Normalize numeric columns (Min-Max).
> 💡 **Hint:** `(df["col"] - df["col"].min()) / (df["col"].max() - df["col"].min())` — result is in range [0, 1].

In [85]:
(df["salary"] - df["salary"].min()) / (df["salary"].max() - df["salary"].min())

0    0.000000
1    0.016667
2    0.008333
3    0.033333
4    0.003333
5    1.000000
6    0.013333
7    0.018333
8    0.015000
9    0.000000
Name: salary, dtype: float64

### Q74. Scale numerical data (Z-score standardization).
> 💡 **Hint:** `(df["col"] - df["col"].mean()) / df["col"].std()` — result has mean=0 and std=1.

In [86]:
(df["salary"] - df["salary"].mean()) / df["salary"].std()

0   -0.354574
1   -0.301254
2   -0.327914
3   -0.247935
4   -0.343910
5    2.844586
6   -0.311918
7   -0.295922
8   -0.306586
9   -0.354574
Name: salary, dtype: float64

### Q75. Rank values in a column.
> 💡 **Hint:** `df["col"].rank()` — use `ascending=False` for descending rank, `method="dense"` to avoid gaps.

In [87]:
df["salary"].rank(ascending=False, method="dense")

0    9.0
1    4.0
2    7.0
3    2.0
4    8.0
5    1.0
6    6.0
7    3.0
8    5.0
9    9.0
Name: salary, dtype: float64

### Q76. Create bins using `cut()`.
> 💡 **Hint:** `pd.cut(df["col"], bins=4)` for equal-width bins or `pd.cut(df["col"], bins=[0,25,50,75,100], labels=["Low","Mid","High","Top"])` for custom intervals.

In [88]:
pd.cut(df["age"], bins=[0, 25, 30, 35, 100], labels=["Young", "Mid", "Senior", "Veteran"])

0      Young
1        Mid
2     Senior
3        Mid
4        NaN
5    Veteran
6     Senior
7        Mid
8    Veteran
9      Young
Name: age, dtype: category
Categories (4, object): ['Young' < 'Mid' < 'Senior' < 'Veteran']

### Q77. Create bins using `qcut()`.
> 💡 **Hint:** `pd.qcut(df["col"], q=4)` for **equal-frequency** (quantile-based) bins. Use `labels=["Q1","Q2","Q3","Q4"]` for named bins.

In [89]:
pd.qcut(df["salary"], q=4, labels=["Q1", "Q2", "Q3", "Q4"])

0    Q1
1    Q3
2    Q2
3    Q4
4    Q1
5    Q4
6    Q2
7    Q4
8    Q3
9    Q1
Name: salary, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

### Q78. Count unique values.
> 💡 **Hint:** `df["col"].nunique()` for the count, `df["col"].value_counts()` for frequency per unique value.

In [90]:
print("Unique departments:", df["department"].nunique())
df["department"].value_counts()

Unique departments: 3

department
HR         4
IT         4
Finance    2
Name: count, dtype: int64

### Q79. Replace multiple values at once.
> 💡 **Hint:** `df.replace({"col": {"old1": "new1", "old2": "new2"}})` or use a list: `df.replace(["old1","old2"], "new")`.

In [91]:
sample = pd.Series(["A", "B", "C", "A", "B"])
print(sample.replace({"A": "Alpha", "B": "Beta"}))
print(sample.replace(["A", "B"], "Group1"))

0    Alpha
1     Beta
2        C
3    Alpha
4     Beta
dtype: object
0    Group1
1    Group1
2         C
3    Group1
4    Group1
dtype: object

### Q80. Create flag column based on condition.
> 💡 **Hint:** `df["flag"] = (df["col"] > threshold).astype(int)` — converts True/False to 1/0. Or use `np.where(condition, 1, 0)`.

In [92]:
df80 = df.copy()
df80["high_earner"] = (df80["salary"] > 60000).astype(int)
df80[["name", "salary", "high_earner"]]

      name  salary  high_earner
0    Alice   50000            0
1      Bob   60000            0
2  charlie   55000            0
3    DAVID   70000            1
4      Eve   52000            0
5    Frank  650000            1
6    Grace   58000            0
7    Heidi   61000            1
8     Ivan   59000            0
9    Alice   50000            0

## 🔹 Section 5: Iteration, GroupBy & Pivot (Q81–Q100)

### Q81. Iterate over rows using `iterrows()`.
> 💡 **Hint:** `for idx, row in df.iterrows():` — `idx` is the index label, `row` is a Series with column values.

In [93]:
for idx, row in df.head(3).iterrows():
    print(idx, row["name"], row["salary"])

0 Alice 50000
1 Bob 60000
2 charlie 55000

### Q82. Iterate using `itertuples()`.
> 💡 **Hint:** `for row in df.itertuples():` — `row.col_name` accesses values. **Faster** than `iterrows()` due to named tuples.

In [94]:
for row in df.head(3).itertuples():
    print(row.Index, row.name, row.salary)

0 Alice 50000
1 Bob 60000
2 charlie 55000

### Q83. Iterate over columns.
> 💡 **Hint:** `for col in df.columns:` then access `df[col]`. Or use `df.items()` which yields `(col_name, Series)` pairs.

In [ ]:
for col in df.columns:
    print(col, "->", df[col].dtype)

### Q84. Avoid iteration using vectorization.
> 💡 **Hint:** Replace `for` loops with direct column operations: `df["new"] = df["a"] * 2 + 1` instead of a loop over rows.

In [ ]:
df84 = df.copy()
df84["double_salary_plus1"] = df84["salary"] * 2 + 1
df84[["salary", "double_salary_plus1"]]

### Q85. Group data using `groupby()`.
> 💡 **Hint:** `df.groupby("col")["value_col"].mean()` — specify the grouping key and the aggregation in one line.

In [ ]:
df.groupby("department")["salary"].mean()

### Q86. Calculate sum per group.
> 💡 **Hint:** `df.groupby("col")["value"].sum()` — replace `sum` with any aggregation function.

In [ ]:
df.groupby("department")["salary"].sum()

### Q87. Calculate multiple aggregations.
> 💡 **Hint:** `df.groupby("col").agg({"col1": "mean", "col2": "sum"})` or `df.groupby("col").agg(name=("col","func"))` for named aggregation.

In [ ]:
df.groupby("department").agg(
    avg_salary=("salary", "mean"),
    max_age=("age", "max")
)

### Q88. Group by multiple columns.
> 💡 **Hint:** `df.groupby(["col1","col2"])["value"].mean()` — pass a list of column names.

In [ ]:
df88 = df.copy()
df88["seniority"] = np.where(df88["age"] >= 35, "Senior", "Junior")
df88.groupby(["department", "seniority"])["salary"].mean()

### Q89. Filter grouped data.
> 💡 **Hint:** `df.groupby("col").filter(lambda g: g["value"].mean() > threshold)` — keeps entire groups satisfying the condition.

In [ ]:
df.groupby("department").filter(lambda g: g["salary"].mean() > 55000)

### Q90. Transform grouped data using `transform()`.
> 💡 **Hint:** `df.groupby("col")["value"].transform("mean")` — returns a Series **same size as the original DataFrame** filled with group statistics.

In [ ]:
df90 = df.copy()
df90["dept_avg_salary"] = df90.groupby("department")["salary"].transform("mean")
df90[["name", "department", "salary", "dept_avg_salary"]]

### Q91. Apply custom function in groupby.
> 💡 **Hint:** `df.groupby("col")["value"].agg(lambda s: s.max() - s.min())` — pass any function that takes a Series and returns a scalar.

In [ ]:
df.groupby("department")["salary"].agg(lambda s: s.max() - s.min())

### Q92. Create basic pivot table.
> 💡 **Hint:** `pd.pivot_table(df, values="val", index="row_col", columns="col_col", aggfunc="mean")`.

In [ ]:
pd.pivot_table(df, values="salary", index="department", aggfunc="mean")

### Q93. Use multiple aggregation functions in pivot.
> 💡 **Hint:** Pass a list to `aggfunc`: `aggfunc=["mean","max"]` — the result will have a MultiLevel column header.

In [ ]:
pd.pivot_table(df, values="salary", index="department", aggfunc=["mean", "max"])

### Q94. Handle missing values in pivot tables.
> 💡 **Hint:** Use `fill_value=0` in `pivot_table()` to replace NaN with a specific value.

In [ ]:
pd.pivot_table(df, values="salary", index="department", columns="city", aggfunc="mean", fill_value=0)

### Q95. Add margins (totals) in pivot tables.
> 💡 **Hint:** `margins=True, margins_name="TOTAL"` in `pivot_table()` adds a summary row and column.

In [ ]:
pd.pivot_table(df, values="salary", index="department", aggfunc="mean", margins=True, margins_name="TOTAL")

### Q96. Create multi-level pivot table.
> 💡 **Hint:** Pass lists to `index` and `columns` parameters: `index=["col1","col2"], columns=["col3"]`.

In [ ]:
df96 = df.copy()
df96["seniority"] = np.where(df96["age"] >= 35, "Senior", "Junior")
pd.pivot_table(df96, values="salary", index=["department", "seniority"], aggfunc="mean")

### Q97. Convert DataFrame to pivot format.
> 💡 **Hint:** `df.pivot(index="row_key", columns="col_key", values="value")` — requires **unique** combinations of row/column keys (no aggregation).

In [ ]:
weather = pd.DataFrame({
    "date": ["2024-01-01", "2024-01-01", "2024-01-02", "2024-01-02"],
    "city": ["Pune", "Mumbai", "Pune", "Mumbai"],
    "temp": [30, 32, 31, 33]
})
weather.pivot(index="date", columns="city", values="temp")

### Q98. Compare pivot vs groupby.
> 💡 **Hint:** `groupby()` is more flexible and returns a flat structure. `pivot_table()` gives a 2D grid and handles duplicates with aggregation. `pivot()` does **no aggregation** and fails on duplicates.

In [ ]:
print("groupby result:")
print(df.groupby("department")["salary"].mean())

print("\npivot_table result:")
print(pd.pivot_table(df, values="salary", index="department", aggfunc="mean"))

### Q99. Build summary report using pivot table.
> 💡 **Hint:** Combine `pivot_table()` with `margins=True` and `fill_value=0`. Chain `.round(2)` for presentation. Export with `.to_csv()` or `.to_excel()`.

In [ ]:
report = pd.pivot_table(
    df,
    values="salary",
    index="department",
    aggfunc=["mean", "sum", "count"],
    margins=True,
    margins_name="TOTAL",
    fill_value=0
).round(2)
report

### Q100. Create an end-to-end analysis workflow.
> 💡 **Hint:** Follow this pipeline:
> 1. Load data → 2. Inspect (shape, dtypes, nulls) → 3. Clean (fillna, drop_duplicates) → 4. Feature engineer → 5. GroupBy/pivot analysis → 6. Sort and rank → 7. Export results.

In [ ]:
# 1. Load
df100 = df.copy()

# 2. Inspect
print("Shape:", df100.shape)
print("Dtypes:\n", df100.dtypes)
print("Nulls:\n", df100.isnull().sum())

# 3. Clean
df100["age"] = df100["age"].fillna(df100["age"].mean())
df100 = df100.drop_duplicates(subset=["name"])
df100["city"] = df100["city"].str.strip().str.title()

# 4. Feature engineer
df100["salary_band"] = pd.cut(
    df100["salary"], bins=[0, 55000, 65000, 1_000_000],
    labels=["Low", "Mid", "High"]
)

# 5. GroupBy / pivot analysis
summary = df100.groupby("department")["salary"].agg(["mean", "sum", "count"]).round(2)

# 6. Sort and rank
df100["salary_rank"] = df100["salary"].rank(ascending=False)

# 7. Export
df100.to_csv("employee_analysis.csv", index=False)
print("Exported to employee_analysis.csv")
summary

---
*📌 Remember: Try solving each question on your own before checking the answer here.*
*⭐ Happy Learning Pandas!*