In [ ]:
#pandas series

In [ ]:
#series from list
import numpy as np
import pandas as pd

#string

country=['india','pakistan','us','uk','china']

pd.Series(country)


#integer

marks=[54,65,69,85,95]
pd.Series(marks)


#custom index

marks=[54,65,69,85,95]
sub=['english','maths','science','geo','history']

pd.Series(marks, index=sub,dtype=np.int32)

#setting names

pd.Series(marks, index=sub, name='amit')

english    54
maths      65
science    69
geo        85
history    95
Name: amit, dtype: int64

In [ ]:
#series from dict

marks={
    "eng":55,
    "maths":65,
    "sci":70,
    "geo":92,
    "history":95
}

pd.Series(marks)

eng        55
maths      65
sci        70
geo        92
history    95
dtype: int64

In [ ]:
#Series using csv.files

#with one coloumn
import pandas as pd
subs=pd.read_csv("/content/subs.csv").squeeze("columns")
subs

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [ ]:
#with 2 columns

vk=pd.read_csv("/content/kohli_ipl.csv", index_col="match_no").squeeze("columns")

In [ ]:
movies=pd.read_csv("/content/bollywood.csv",index_col="movie").squeeze("columns")
movies.value_counts().head(5).is_unique

True

In [ ]:
import pandas as pd

s = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
s

a    10
b    20
c    30
d    40
dtype: int64

In [ ]:
#series methods
#head&tail
vk.head(10)

vk.tail()

match_no
211     0
212    20
213    73
214    25
215     7
Name: runs, dtype: int64

In [ ]:
#sample()    fetch ramdom item
vk.sample()

match_no
54    35
Name: runs, dtype: int64

In [ ]:
#value_counts           value_counts() is used to count the occurrences of each unique value in a Series

subs.value_counts(ascending=False)

Subscribers gained
105    9
108    6
88     5
72     5
123    5
      ..
177    1
209    1
231    1
226    1
144    1
Name: count, Length: 180, dtype: int64

In [ ]:
#sort_values

subs.sort_values()

subs.sort_index()

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [ ]:
#series maths methods
#count     count() returns the number of non-missing (non-NaN) values in a Series or DataFrame.
movies.count()

s = pd.Series([10, 20, np.nan, 40, 50])

print(s.count())

4

In [ ]:
#sum(),prod()

vk.sum()
movies.sum()
subs.sum()
subs.prod()

0

In [ ]:
#mean/mode/meadian/std/var/min/max

In [ ]:
#describe

vk.describe()

count    215.000000
mean      30.855814
std       26.229801
min        0.000000
25%        9.000000
50%       24.000000
75%       48.000000
max      113.000000
Name: runs, dtype: float64

In [ ]:
#series indexing and slicing

#indexing
movies[0]
movies[-1]
vk.iloc[-1]
vk

/tmp/ipykernel_6787/2415573317.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  movies[0]
/tmp/ipykernel_6787/2415573317.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  movies[-1]

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64