In [ ]:
import pandas as pd
vk = pd.read_csv("/content/kohli_ipl.csv")
#vk[(vk >= 50)&(vk<=99)].size
vk

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

In [ ]:
#creating a dataframe

data={
    "name":["Amit","Rupesh","Sharad","Shubham"],
    "age":[22,25,21,24],
    "city":["pune","mumbai","delhi","pune"]
}

df=pd.DataFrame(data)
df

      name  age    city
0     Amit   22    pune
1   Rupesh   25  mumbai
2   Sharad   21   delhi
3  Shubham   24    pune

In [ ]:
#Print:
#shape
df.shape
#size
df.size
#ndim
df.ndim
#columns
df.columns
#index
df.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
#Q3

#Print the first 2 rows.

df.head(2)

#Q4
#Print the last 3 rows.
df.tail(3)

#Q5

#Print one random row.
df.sample(1)

      name  age  city
3  Shubham   24  pune

In [ ]:
#Level 2: Data Inspection
#Q6

#Display complete information about the DataFrame.

df.info()

#Q7

#Show statistical summary.
df.describe()

#Q8

#Find:

#maximum age
df["age"].max()
#minimum age
df["age"].min()
#average age
df["age"].mean()
#Q9

#Count total non-null values in each column.
df.count()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      object
 1   age     4 non-null      int64
 2   city    4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

name    4
age     4
city    4
dtype: int64

In [ ]:
#Q10

#Select only the Name column.
df["name"]

#Q11

#Select Name and City columns together.
df[["name","city"]]

#Q12

#Print the datatype of each column.
df[["name","age"]].dtypes
df.dtypes

name    object
age      int64
city    object
dtype: object

In [ ]:
#Level 4: Row Selection
#Q13

#Print the first row using iloc.
df.iloc[0]     #output in series
df.iloc[[0]]   #as dataframe


#Q14

#Print rows 1 to 3 using iloc.

df.iloc[[1,2,3]]

#Q15

#Print the row having index 2 using loc.
#df.loc[2]

      name  age    city
1   Rupesh   25  mumbai
2   Sharad   21   delhi
3  Shubham   24    pune

In [ ]:
#Level 5: Filtering
#Q16

#Show students whose age is greater than 22.
df[df["age"]>22].shape[0]

#Q17

#Show students from Pune.
df[df['city']=="pune"]

#Q18

#Show students whose age is greater than 22 and city is Pune.
df[(df["age"]>22) & (df["city"]=="pune")]

#Q19

#Show students whose age is either 21 or 24.
df[(df["age"]==21) | (df["age"]==24)]

      name  age   city
2   Sharad   21  delhi
3  Shubham   24   pune

In [ ]:
#Level 6: Sorting
#Q20

#Sort students by age in ascending order.
df.sort_values(by="age",ascending=True)
#df["age"].sort_values(ascending=False)

#Q21

#sort students by age in descending order.

df.sort_values(by="age",ascending=False)

#Q22

Sort students by city name.
df.sort_values(by="city")

      name  age    city
2   Sharad   21   delhi
0     Amit   22    pune
3  Shubham   24    pune
1   Rupesh   25  mumbai

In [ ]:
#Level 7: Adding and Updating
#Q23

#Add a new column:

#Salary = [30000,40000,35000,45000]

df["Salary"]=[30000,40000,35000,45000]
df
#Q24

#Increase every salary by 5000 using apply().

df["Salary"]=df.loc["Salary"].apply(lambda x: x+5000)
df

#Q25

#Change Amit's age from 22 to 23.

df.loc[df["name"]=="Amit","age"]=23
df

KeyError: 'Salary'

In [ ]:
df = pd.DataFrame({
    'Name':['Amit',None,'Neha','Ravi'],
    'Age':[22,25,None,21],
    'Marks':[80,None,90,85]
})


#Q26

#Find total missing values in each column.

df.isnull().sum()

#Q27

#Fill all missing values with 0.
df.fillna(0)
df
#Q28
#Fill missing age with average age.
df["Age"]=df["Age"].fillna(df["Age"].mean())
df

##Q29

#Remove rows containing missing values.

df.dropna()

   Name        Age  Marks
0  Amit  22.000000   80.0
2  Neha  22.666667   90.0
3  Ravi  21.000000   85.0

In [ ]:
df = pd.DataFrame({
    'Name':['Amit','Ravi','Amit','Neha'],
    'Age':[22,25,22,21]
})

#Q30

#Check duplicate rows.
df.duplicated()

#Q31

#Show only duplicate rows.
df[df.duplicated()]

#Q32

#Remove duplicate rows.
df.drop_duplicates()

#Q33

#Count total duplicate rows.
df.duplicated().sum()

np.int64(1)

In [ ]:
#Level 10: Rename and Drop
#Q34

#Rename column Age to Student_Age.

df.rename(columns={"Age":"Student_Age"})
#Q35

#Rename column Name to Student_Name.

df.rename(columns={"Name":"Student_Name"})


#Q36

#Drop the City column.
df.drop(columns=["city"])

#Q37

#Drop the first row.
df.drop(1)

      name  age   city
0     Amit   22   pune
2   Sharad   21  delhi
3  Shubham   24   pune

In [ ]:
df = pd.DataFrame({
    'City':['Pune','Mumbai','Pune','Delhi','Mumbai','Pune']
})

#Q38

#Count frequency of each city.

df.value_counts()


#Q39

#Find city percentages using normalize=True.

df["City"].value_counts(normalize=True)*100


#Q40

#Which city appears most frequently?
df["City"].value_counts().idxmax()

'Pune'

In [ ]:
df = pd.DataFrame({
    'Department':['IT','HR','IT','HR','Sales'],
    'Salary':[50000,40000,60000,45000,55000]
})

#Q41

#Find average salary department-wise.

x=df.groupby("Department")["Salary"].mean()
x

#Q42

#Find maximum salary department-wise.

x=df.groupby("Department")["Salary"].max()
x
#Q43

#Find total salary department-wise.
x=df.groupby("Department")["Salary"].sum()
x

Department
HR        85000
IT       110000
Sales     55000
Name: Salary, dtype: int64

In [ ]:
data={
    "name":["Amit","Rupesh","Sharad","Shubham"],
    "age":[22,25,21,24],
    "city":["pune","mumbai","delhi","pune"]
}

df=pd.DataFrame(data)
df
#Q44

#Make Name the index.
df=df.set_index("name")

#Q45

#Access Amit's record using .loc.
df.loc["Amit"]

#Q46

#Reset the index.

df.reset_index()

#Q47

#Reset index and remove old index completely.

df.reset_index(drop=True)

   age    city
0   22    pune
1   25  mumbai
2   21   delhi
3   24    pune

In [ ]:
data = {
    'Name':['Amit','Ravi','Neha','Karan','Amit'],
    'Age':[22,25,21,24,22],
    'Marks':[85,90,None,88,85],
    'City':['Pune','Mumbai','Delhi','Pune','Pune']
}

df=pd.DataFrame(data)


#Find shape of DataFrame.

df.shape

#Show first 3 rows.
df.head(3)
#Find missing values.
df.isnull().sum()

#Fill missing marks with average marks.

#df=df["Marks"].fillna(df["Marks"].mean())

#Count students city-wise.
df.groupby("City")["Name"].count().sort_values(ascending=False)
df["City"].value_counts()
df
#Remove duplicate rows.
df.drop_duplicates()
#Sort by marks descending.
df.sort_values(by="Marks",ascending=False)
df["Marks"].sort_values(ascending=False)
#Make Name as index.
df.set_index("Name")
#Reset index.
df.reset_index()
#Find average marks.
df["Marks"].mean()

#find avg for all numeric values in table

df.mean(numeric_only=True)

Age      22.8
Marks    87.0
dtype: float64

In [ ]:
import pandas as pd

x = {
    "Name": ["Amit", "Rohit", "Amit", "Neha", "Rohit", "Neha", "Amit", "Rohit"],
    "City": ["Pune", "Mumbai", "Pune", "Delhi", "Mumbai", "Delhi", "Pune", "Mumbai"],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "Finance", "IT", "HR"],
    "Salary": [50000, 45000, 55000, 60000, 48000, 62000, 58000, 50000],
    "Age": [22, 25, 23, 30, 26, 31, 24, 27]
}

df = pd.DataFrame(x)
df

#Easy Level
#1.
#Group by Name and find the total salary.

df.groupby("Name")["Salary"].sum()

#2.
#Group by Department and find the average salary.

df.groupby("Department")["Salary"].mean()

#3.

#Count how many employees belong to each city.

df["City"].value_counts()
df.groupby("City")["Name"].count()

#4.

#Find the maximum age in each department.
df.groupby("Department")["Age"].max()


#Find the maximum age in each department with name

df.loc[df.groupby("Department")["Age"].idxmax(),["Department","Name","Age"]]

#5.

#Find the minimum salary for each city.
df.groupby("City")["Salary"].min()


#6.

#Find the number of employees in each department.
df.groupby("Department")["Name"].count()

#7.

#Find the average age of employees in each city.

df.groupby("City")["Age"].mean()

#8.

#Find the highest salary earned by each employee.
df.groupby('Name')["Salary"].max()

#9.

#Find the lowest age for each department.
df.groupby("Department")["Age"].min()

#Find the lowest age for each department with name.
df.loc[df.groupby("Department")["Age"].idxmin(),["Name","Department","Age"]]

#10.

#Find salary sum city-wise.

df.groupby("City")["Salary"].sum()

City
Delhi     122000
Mumbai    143000
Pune      163000
Name: Salary, dtype: int64